# Generated by Django 5.2.1 on 2026-04-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('to_email', models.EmailField(max_length=254)),
                ('cc_email', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('attachment_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplateTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, unique=True)),
                ('source_table', models.CharField(max_length=100)),
                ('source_field', models.CharField(max_length=100)),
                ('relation_key', models.CharField(blank=True, max_length=100)),
                ('module_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(db_index=True, max_length=100)),
                ('module_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('to_send', models.BooleanField(default=True)),
                ('to_type', models.CharField(choices=[('customer', 'Customer'), ('user', 'User'), ('dynamic', 'Dynamic'), ('static', 'Static')], max_length=20)),
                ('to_value', models.CharField(max_length=255)),
                ('is_cc', models.BooleanField(default=False)),
                ('cc_type', models.CharField(blank=True, choices=[('static', 'Static'), ('dynamic', 'Dynamic')], max_length=20)),
                ('cc_value', models.CharField(blank=True, max_length=500)),
                ('subject_template', models.CharField(max_length=500)),
                ('body_template', models.TextField()),
                ('attach_pdf', models.BooleanField(default=False)),
                ('pdf_template_code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('event_name', 'module_name')},
            },
        ),
    ]
