# Generated by Django 5.2.1 on 2026-04-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email Log', 'verbose_name_plural': 'Email Logs'},
        ),
        migrations.AlterModelOptions(
            name='emailmaster',
            options={'ordering': ['module_name', 'event_name'], 'verbose_name': 'Email Rule', 'verbose_name_plural': 'Email Rules'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplatetag',
            options={'ordering': ['module_name', 'tag_name'], 'verbose_name': 'Template Tag', 'verbose_name_plural': 'Template Tags'},
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='attachment_path',
            field=models.CharField(blank=True, default='', help_text='Filesystem path to the attached PDF, if any.', max_length=500),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='cc_email',
            field=models.TextField(blank=True, default='', help_text='Comma-separated CC addresses.'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text="Populated when status is 'failed'."),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='event_name',
            field=models.CharField(db_index=True, help_text='The event that triggered this email.', max_length=100),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='to_email',
            field=models.EmailField(help_text='Recipient email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailmaster',
            name='attach_pdf',
            field=models.BooleanField(default=False, help_text='Whether to attach a PDF to the email.'),
        ),
        migrations.AlterField(
            model_name='emailmaster',
            name='body_template',
            field=models.TextField(help_text='HTML body with {{tag}} placeholders.'),
        ),
        migrations.AlterField(
            model_name='emailmaster',
            name='cc_type',
            field=models.CharField(blank=True, choices=[('static', 'Static'), ('dynamic', 'Dynamic')], default='', help_text='How the CC address is resolved.', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailmaster',
            name='cc_value',
            field=models.CharField(blank=True, default='', help_text='CC field path or comma-separated static emails.', max_length=500),
        ),
        migrations.AlterField(
            model_name='emailmaster',
            name='event_name',
            field=models.CharField(db_index=True, help_text="Business event identifier, e.g. 'enquiry_created'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='emailmaster',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Disabled rules are ignored by the engine.'),
        ),
        migrations.AlterField(
            model_name='emailmaster',
            name='is_cc',
            field=models.BooleanField(default=False, help_text='Whether CC recipients should be included.'),
        ),
        migrations.AlterField(
            model_name='emailmaster',
            name='module_name',
            field=models.CharField(help_text="Module/app that owns this event, e.g. 'crm'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='emailmaster',
            name='pdf_template_code',
            field=models.CharField(blank=True, default='', help_text="Key into the PDF_REGISTRY, e.g. 'enquiry_pdf'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='emailmaster',
            name='subject_template',
            field=models.CharField(help_text='Subject line with {{tag}} placeholders.', max_length=500),
        ),
        migrations.AlterField(
            model_name='emailmaster',
            name='to_send',
            field=models.BooleanField(default=True, help_text='Master toggle — set to False to suppress sending.'),
        ),
        migrations.AlterField(
            model_name='emailmaster',
            name='to_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('user', 'User'), ('dynamic', 'Dynamic'), ('static', 'Static')], help_text='How the TO address is resolved.', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailmaster',
            name='to_value',
            field=models.CharField(help_text="Dotted field path (e.g. 'customer.email') or a static email address.", max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtemplatetag',
            name='module_name',
            field=models.CharField(help_text='Module this tag belongs to.', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailtemplatetag',
            name='relation_key',
            field=models.CharField(blank=True, default='', help_text='FK/relation path to traverse from the event instance.', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailtemplatetag',
            name='source_field',
            field=models.CharField(help_text='Field name on the source model.', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailtemplatetag',
            name='source_table',
            field=models.CharField(help_text='Django model (app_label.ModelName) that holds the data.', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailtemplatetag',
            name='tag_name',
            field=models.CharField(help_text="Tag identifier used in templates, e.g. 'customer_name'.", max_length=100, unique=True),
        ),
    ]
