# Generated by Django 5.2.1 on 2025-05-24 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='base.gender'),
        ),
    ]
