# Generated by Django 5.2.1 on 2026-03-26 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_person_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Gender', to='base.gender'),
        ),
    ]
