# Generated by Django 5.2.1 on 2026-03-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_person_address_alter_person_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('name', 'address')},
        ),
        migrations.AlterModelTable(
            name='person',
            table='person_details',
        ),
    ]
